version: "3.9"

services:
  odoo:
    build: .  # This will use our local Dockerfile
    container_name: "odoo_app"
    depends_on:
      db: 
        condition: "service_healthy"
    ports:
      - "8069:8069"
    volumes:
      - "odoo-data:/var/lib/odoo"
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    environment:
      - "HOST=db"
      - "USER=odoo"
      - "PASSWORD_FILE=/run/secrets/postgresql_password"
    secrets:
      - "postgresql_password"
    networks:
      - "odoo-net"
    restart: "unless-stopped"

  db:
    image: "postgres:16"
    container_name: "odoo_db"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=odoo"
      - "POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    secrets:
      - "postgresql_password"
    networks:
      - "odoo-net"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: "10s"
      timeout: "5s"
      retries: 5
    restart: "unless-stopped"

volumes:
  odoo-data:
  db-data:

secrets:
  postgresql_password:
    file: "./secrets/postgresql_password.txt"

networks:
  odoo-net:
    driver: "bridge"

